name: opus_flutter_example
description: Demonstrates how to use the opus_flutter plugin.
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_share: ^1.0.2+1
  path_provider: ^1.6.10
  opus_flutter:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/s16le_16000hz_mono.raw