name: opus_flutter_android
description: Android implementation of the opus_flutter plugin.
repository: https://github.com/EPNW/opus_flutter/tree/master/opus_flutter_android
version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  opus_flutter_platform_interface:
    path: ../opus_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
#        package: eu.epnw.opus_flutter_android
        pluginClass: OpusFlutterAndroid
        fileName: opus_flutter_android.dart