name: opus_flutter_example
description: Demonstrates how to use the opus_flutter plugin.
version: 2.0.0+2
publish_to: "none"

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  opus_dart: ^3.0.1
  flutter:
    sdk: flutter
  share_plus: ^7.2.1
  opus_flutter:
    path: ../
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/s16le_16000hz_mono.raw
    - assets/download.js
