name: opus_flutter_example
description: Demonstrates how to use the opus_flutter plugin.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  opus_dart: ^2.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  share: ^2.0.1
  path_provider: ^2.0.1
  opus_flutter:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/s16le_16000hz_mono.raw